[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Handle specific redirects if needed
# [[redirects]]
#   from = "/old-path"
#   to = "/new-path"
#   status = 301

# Optional: Handle API redirects if you have a backend
# [[redirects]]
#   from = "/api/*"
#   to = "https://your-api-domain.com/api/:splat"
#   status = 200

# Optional: Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Optional: Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
